### ISSUE TITLE
Licensing and build documentation

### ISSUE THREAD

**Issue by srinathh** [zichongkao/selectstarsql#2]
Is there any chance of republishing this with CC0/MIT licensing? I'd love to trial using this to run SQL workshops in my company to teach people basics of SQL modifying some of the data/code appropriate to my context. Alternatively, are you planning for a licensing model for use in a commercial setting?

**Comment by zichongkao** [comment]
@srinathh Sorry I missed your message. Let me think about this for a bit and get back to you.

**Comment by zichongkao** [comment]
Would this license work for you? https://creativecommons.org/licenses/by-sa/4.0/. It permits commercial use

**Comment by srinathh** [comment]
Yup that would be perfect!

**Comment by srinathh** [comment]
Any luck with allowing CC-BY-SA-4 licensing as above? I believe the license  still says Non Commerfial in the Readme

**Comment by zichongkao** [comment]
It's been changed to CC-BY-SA-4 already :)

**Comment by srinathh** [comment]
Super! Thanks!
