### ISSUE TITLE
The interactive SQL editor is not working

### ISSUE THREAD

**Issue by Hipposterous** [zichongkao/selectstarsql#25]
![image](https://user-images.githubusercontent.com/4388048/172756641-504c1747-cbaf-4dc1-acee-b952543048dc.png)

**Comment by kiinoda** [comment]
This is why I came here, as well.

It is working in Opera on my M1 Mac.

Here's a rundown of versions and results:

* Opera v88.0.4412.40 (arm64) (Mac) - WORKING
* Safari 15.5 (17613.2.7.1.8) (arm65) (Mac) - NOT working
* Chrome 102.0.5005.61 (Official Build) (arm64)(Mac) - NOT working
* Firefox 101.0.1 (64-bit) (Mac) - NOT working

**Comment by Hipposterous** [comment]
It appears to be fixed. Thank you.
