### ISSUE TITLE
"Proportion of last statements with claims of innocence" is ambiguous?

### ISSUE THREAD

**Issue by alexpeattie** [zichongkao/selectstarsql#3]
At the end of Chapter 2, the reader's asked to calculate the proportion of last statements with a claim of innocence. The right answer is given as:

```sql
SELECT
1.0 * COUNT(CASE WHEN last_statement LIKE '%innocent%'
    THEN 1 ELSE NULL END) / COUNT(*)
FROM executions
```

However, I think a more natural answer (given how the question is phrased) would be:

```sql
SELECT
1.0 * COUNT(CASE WHEN last_statement LIKE '%innocent%'
    THEN 1 ELSE NULL END) / COUNT(statements)
FROM executions
```

Since 443 last statements were given, and 31 claim innocence, which ≈ 7%. But I think it would be fine to stick with the former answer, but then maybe the question could be clarified by rephrasing it to something like:

**"Find the proportion of inmates who claim innocence in their last statement."**

**Comment by Knaspast** [comment]
+1

**Comment by Knaspast** [comment]
bump

**Comment by zichongkao** [comment]
Thanks. You guys are right. I've rephrased the question to better match the intent.

**Comment by alexpeattie** [comment]
Awesome 👍
